# Generated by Django 5.1.4 on 2024-12-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sku_id', models.CharField(max_length=255, unique=True)),
                ('nums', models.IntegerField()),
                ('is_delete', models.IntegerField()),
            ],
            options={
                'db_table': 'shopping_cart_one',
            },
        ),
    ]
