# Generated by Django 5.1.4 on 2025-01-06 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'managed': False},
        ),
    ]
